server:
  port: 8099
spring:
  rabbitmq:
    host: 127.0.0.1
  application:
    name: rabbitmq
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
